openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Books"
  - name: "Users"


paths:

  /books:

    post:
      summary: Creates a book
      operationId: createBook
      requestBody:
        description: HELLO
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        "201":
          description: CREATED

    get:
      summary: This gets all books
      description: This is a detailed description
      tags:
        - "Books"
      operationId: getAllBooksInLibrary
      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH

  /books/{bookId}:
    parameters:
      - name: bookId
        description: book id
        schema:
          type: string
        in: path
        required: true
    get:
      summary: Get a book by Id
      operationId: Get a book by Id
      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'



components:

  schemas:

    Book:
      description: This is the book model
      type: object
      required:
        - name
      properties:
        name:
          description: The name of book
          type: string
        bookAuthor:
          description: name of author
          type: string