openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Books"
  - name: "Users"


paths:

  /books:
    get:
      summary: This gets all books
      description: This is a detailed description
      tags:
        - "Books"
      operationId: getAllBooksInLibrary
      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH

components:

  schemas:

    Book:
      description: This is the book model
      type: object
      properties:
        name:
          description: The name of book
          type: string
        bookAuthor:
          description: name of author
          type: string